# lecture05
# make
lecture06:
	g++ -Wall -Werror -O1 -pedantic ./lecture06.cpp -o lecture06
clean06:
	rm lecture06
lecture05:
	g++ -Wall -Werror -O1 -pedantic lecture05.cpp -o lecture05
clean05:
	rm lecture05
# lecture04
# make
lecture04:
	g++ -Wall -Werror -O1 -pedantic lecture04.cpp -o lecture04
clean04:
	rm lecture04

clean_all:
	rm lecture06 lecture05 lecture04
